/**
 * Regenerate configs/settlers.json from the 0x Deployer's ERC721 Transfer logs.
 *
 * Run:  npm run settlers:refresh
 *
 * Rotation happens a few times a year, so this is on-demand, and its output is
 * committed and reviewed as a diff. The whole history fits in ONE unranged
 * eth_getLogs (58 logs as of 2026-07-15) — no block-chunking needed.
 */

import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { parseDeployerTransfers, type SettlersConfig } from '../settlerRegistry.js';

const DEPLOYER = '0x00000000000004533fe15556b1e086bb1a72ceae';
const TRANSFER_TOPIC = '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef';
const CHAIN_ID = 8453;

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.resolve(__dirname, '../../../../configs/settlers.json');

async function rpc(url: string, method: string, params: unknown[]): Promise<unknown> {
	const res = await fetch(url, {
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }),
	});
	const json = (await res.json()) as { result?: unknown; error?: { message: string } };
	if (json.error) throw new Error(`${method} failed: ${json.error.message}`);
	return json.result;
}

async function main(): Promise<void> {
	const rpcUrl = process.env.TCA_RPC_URL;
	if (!rpcUrl) throw new Error('TCA_RPC_URL is not set — export it or source .env');

	const logs = (await rpc(rpcUrl, 'eth_getLogs', [
		{ address: DEPLOYER, topics: [TRANSFER_TOPIC], fromBlock: '0x0', toBlock: 'latest' },
	])) as { topics: string[]; blockNumber: string }[];

	const settlers = parseDeployerTransfers(logs, '0x');
	if (settlers.length === 0) {
		// Never write an empty set — that would silently un-identify every 0x
		// trade. Fail loudly and leave the last-known-good config in place.
		throw new Error('Deployer scan produced 0 settlers — refusing to overwrite config');
	}

	const config: SettlersConfig = {
		_comment:
			'GENERATED by `npm run settlers:refresh` — do not hand-edit. Every address ever ' +
			'registered to a 0x Deployer feature. Identity is a set: `fromBlock` is audit-only ' +
			'and is not consulted at lookup. Features: 2=taker-submitted, 3=gasless/metatxn, ' +
			'4=intents, 5=bridge. Feature 1 is retired (minted 12723120, burned 14859201).',
		generatedAt: new Date().toISOString(),
		deployer: DEPLOYER,
		chainId: CHAIN_ID,
		settlers,
	};

	await writeFile(OUT_PATH, JSON.stringify(config, null, '\t') + '\n', 'utf8');
	const features = [...new Set(settlers.map((s) => s.feature))].sort((a, b) => a - b);
	console.log(`Wrote ${settlers.length} settlers (features ${features.join(', ')}) → ${OUT_PATH}`);
}

main().catch((e: unknown) => {
	console.error(e instanceof Error ? e.message : e);
	process.exit(1);
});
