/**
 * Regenerate configs/reactors.json from live UniswapX `Fill` logs on Base.
 *
 * Run:  npm run reactors:refresh   (requires TCA_RPC_URL)
 *
 * Distinct emitters of the Fill topic over a recent window ARE the reactors —
 * same "authoritative on-chain set" idea as settlers:refresh. Output is
 * committed and reviewed as a diff.
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';
import { FILL_TOPIC0, type ReactorsConfig } from '../settlementDecoders.js';

const CHAIN_ID = 8453;
const WINDOW_BLOCKS = 2_000_000n; // ~6 weeks on Base; widen if the set looks thin
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_PATH = path.resolve(__dirname, '../../../../configs/reactors.json');

async function rpc(url: string, method: string, params: unknown[]): Promise<unknown> {
	const res = await fetch(url, {
		method: 'POST',
		headers: { 'Content-Type': 'application/json' },
		body: JSON.stringify({ jsonrpc: '2.0', id: 1, method, params }),
	});
	const json = (await res.json()) as { result?: unknown; error?: { message: string } };
	if (json.error) throw new Error(`${method} failed: ${json.error.message}`);
	return json.result;
}

// Alchemy (our RPC provider) caps eth_getLogs responses at a 10,000-block
// range OR 10,000 logs, whichever binds first — an unranged query over the
// full WINDOW_BLOCKS throws "Log response size exceeded". Page the scan in
// fixed-size chunks and concatenate; this still derives the reactor set
// purely from live Fill logs, just paginated to respect the provider limit.
const CHUNK_BLOCKS = 500_000n;

async function getLogsChunked(
	rpcUrl: string,
	fromBlockNum: bigint,
	toBlockNum: bigint,
): Promise<{ address: string; transactionHash: string }[]> {
	const logs: { address: string; transactionHash: string }[] = [];
	for (let start = fromBlockNum; start <= toBlockNum; start += CHUNK_BLOCKS) {
		const end = start + CHUNK_BLOCKS - 1n > toBlockNum ? toBlockNum : start + CHUNK_BLOCKS - 1n;
		const chunk = (await rpc(rpcUrl, 'eth_getLogs', [
			{ topics: [FILL_TOPIC0], fromBlock: '0x' + start.toString(16), toBlock: '0x' + end.toString(16) },
		])) as { address: string; transactionHash: string }[];
		logs.push(...chunk);
	}
	return logs;
}

async function main(): Promise<void> {
	const rpcUrl = process.env.TCA_RPC_URL;
	if (!rpcUrl) throw new Error('TCA_RPC_URL is not set — export it or source .env');

	const head = BigInt((await rpc(rpcUrl, 'eth_blockNumber', [])) as string);
	const fromBlockNum = head - WINDOW_BLOCKS;
	const logs = await getLogsChunked(rpcUrl, fromBlockNum, head);

	const reactors = [...new Set(logs.map((l) => l.address.toLowerCase()))].sort();
	if (reactors.length === 0) {
		throw new Error('Fill scan produced 0 reactors — widen WINDOW_BLOCKS or check the RPC; refusing to overwrite config');
	}

	const config: ReactorsConfig = {
		_comment:
			'GENERATED by `npm run reactors:refresh` — do not hand-edit. Distinct emitters of the ' +
			'UniswapX Fill topic on Base. Review the diff before committing (a stray emitter here ' +
			'would let a non-UniswapX contract re-anchor a trade).',
		generatedAt: new Date().toISOString(),
		chainId: CHAIN_ID,
		reactors,
	};
	await writeFile(OUT_PATH, JSON.stringify(config, null, '\t') + '\n', 'utf8');
	// Print sample fill txns so the e2e task (Task 7) has real hashes to use.
	const samples = [...new Set(logs.map((l) => l.transactionHash))].slice(0, 5);
	console.log(`Wrote ${reactors.length} reactor(s) → ${OUT_PATH}\nSample Fill txns: ${samples.join(', ')}`);
}

main().catch((e: unknown) => {
	console.error(e instanceof Error ? e.message : e);
	process.exit(1);
});
