// ESLint 9 flat config. `typescript-eslint` has been a devDependency since the
// repo was set up, but no config file ever landed — so `npm run lint` failed
// outright rather than linting anything.
//
// Scope is deliberately narrow: the type-unaware `recommended` preset over
// first-party source only. Build output, generated migrations, and vendored
// files are ignored; enabling the type-checked presets is a separate decision
// (it needs a project service and would surface a large backlog at once).
import tseslint from 'typescript-eslint';

export default tseslint.config(
	{
		ignores: [
			'**/node_modules/**',
			'**/dist/**',
			'**/.next/**',
			'**/drizzle/**',
			'**/*.config.js',
			'**/*.config.mjs',
			// Generated by Next on every dev/build; not ours to edit.
			'**/next-env.d.ts',
		],
	},
	...tseslint.configs.recommended,
	{
		files: ['**/*.{ts,tsx}'],
		languageOptions: {
			parserOptions: { ecmaFeatures: { jsx: true } },
		},
		rules: {
			// The codebase uses leading-underscore params to mark intentional
			// non-use; honour that convention rather than rewriting call sites.
			'@typescript-eslint/no-unused-vars': [
				'error',
				{ argsIgnorePattern: '^_', varsIgnorePattern: '^_', caughtErrors: 'none' },
			],
		},
	},
	{
		// Test fixtures build partial rows and cast them past the real types on
		// purpose — asserting on a hand-written subset is the point. Requiring a
		// full type there would mean inventing fields the assertion doesn't use.
		files: ['**/*.test.{ts,tsx}'],
		rules: { '@typescript-eslint/no-explicit-any': 'off' },
	},
);
