CREATE TABLE IF NOT EXISTS "smoke_trades" (
	"tx_hash" text PRIMARY KEY NOT NULL,
	"aggregator" text NOT NULL,
	"trader" text NOT NULL,
	"direction" text NOT NULL,
	"settled_in" text NOT NULL,
	"usdc_amount" numeric NOT NULL,
	"weth_amount" numeric NOT NULL,
	"realized_price" numeric NOT NULL,
	"market_mid" numeric NOT NULL,
	"all_in_cost_bps" numeric NOT NULL,
	"block_number" integer NOT NULL,
	"lp_fee_bps" numeric,
	"agg_fee_bps" numeric,
	"slippage_bps" numeric,
	"execution_bps" numeric,
	"gas_cost_usd" numeric,
	"route_pure" boolean,
	"experiment_slug" text NOT NULL,
	"run_id" text NOT NULL,
	"v1_status" text NOT NULL,
	"v1_quote_amount_usd" numeric,
	"v1_realized_amount_usd" numeric,
	"settlement_event_name" text,
	"settlement_event_topic0" text,
	"settlement_event_seen" boolean DEFAULT false NOT NULL,
	"normalize_flags" jsonb,
	"loaded_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "smoke_trades_aggregator_idx" ON "smoke_trades" USING btree ("aggregator");