CREATE TABLE IF NOT EXISTS "receipts" (
	"id" serial PRIMARY KEY NOT NULL,
	"tx_hash" text NOT NULL,
	"chain_id" integer NOT NULL,
	"user_id" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"aggregator" text NOT NULL,
	"trader" text NOT NULL,
	"direction" text NOT NULL,
	"input_token" text NOT NULL,
	"output_token" text NOT NULL,
	"input_symbol" text NOT NULL,
	"output_symbol" text NOT NULL,
	"input_amount" numeric NOT NULL,
	"output_amount" numeric NOT NULL,
	"notional_usd" numeric,
	"realized_price" numeric,
	"market_mid" numeric,
	"all_in_cost_bps" numeric,
	"pricing_status" text NOT NULL,
	"block_number" integer NOT NULL,
	"execution_bps" numeric,
	"lp_fee_bps" numeric,
	"agg_fee_bps" numeric,
	"slippage_bps" numeric,
	"gas_cost_usd" numeric,
	"route_pure" boolean,
	"route_shape" text,
	"hop_count" integer,
	"route_legs" jsonb,
	"recon_residual_bps" numeric,
	"decomp_confidence" text,
	"settlement_event_name" text,
	"settlement_event_topic0" text,
	"settlement_event_seen" boolean DEFAULT false NOT NULL,
	"normalize_flags" jsonb,
	"chainlink_price" numeric,
	"chainlink_dev_bps" numeric,
	"pool_divergence_bps" numeric,
	"manipulation_flag" boolean,
	"offchain_price" numeric,
	"offchain_dev_bps" numeric,
	"chainlink_staleness_secs" numeric
);
--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "receipts_user_tx_chain_idx" ON "receipts" USING btree ("user_id","tx_hash","chain_id");